// Keep the public, readable page identical to the policy's plain-text source.
const fs = require('node:fs');
const path = require('node:path');
const publicDir = path.join(__dirname, '..', 'public');
const policy = fs.readFileSync(path.join(publicDir, 'privacy-policy.txt'), 'utf8');
const escaped = policy.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
fs.writeFileSync(path.join(publicDir, 'privacy.html'), `<!DOCTYPE html>
<!-- Generated by scripts/build-policy.cjs from privacy-policy.txt. -->
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="theme-color" content="#f5f3ed">
<title>Privacy policy — All News</title>
<script src="theme.js"></script>
<link rel="icon" href="news-mark.svg" type="image/svg+xml">
<link rel="stylesheet" href="newsroom.css">
</head>
<body>
<main class="contact-page">
<a class="contact-back" href="index.html">← All News</a>
<h1>Privacy policy</h1>
<div class="policy-text">${escaped}</div>
<a class="contact-privacy" href="contact.html">Contact us</a>
<a class="contact-privacy" href="privacy-policy.txt">Plain-text copy</a>
</main>
</body>
</html>
`, 'utf8');
